spring:
  ai:
    openai:
      base-url: http://154.44.25.190:11434
      api-key: ollama-dummy-key
      chat:
        options:
          model: qwen3.5-9b-q8:latest

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/school_db?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: 123456

  data:
    redis:
      host: 192.168.110.110
      port: 6379
      password: LrhiaBMY8oRdzKP4TDdN
      database: 6
      lettuce:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0

mybatis:
  # 指定 XML 映射文件的位置
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 开启驼峰命名自动映射 (tuition_rmb -> tuitionRmb)
    map-underscore-to-camel-case: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
# Knife4j 增强配置
knife4j:
  enable: true # 开启增强功能
  setting:
    language: zh_cn # 界面语言

## 大模型相关配置
#llm:
#  api-url: http://154.44.25.190:11434/api/generate
#  model-name: qwen3.5-9b-q8:latest